### ISSUE TITLE
Convert password text field to a swing JPasswordField?

### ISSUE THREAD

**Issue by truth-quark** [SPECCHIODB/SPECCHIO#1]
For security, would the password text field be safer if changed to a JPasswordField here?
https://github.com/SPECCHIODB/SPECCHIO/blob/master/src/client/src/ch/specchio/gui/UserAccountDialog.java#L613
https://github.com/SPECCHIODB/SPECCHIO/blob/master/src/client/src/ch/specchio/gui/ServerDescriptorPanel.java#L41

JPasswordField API docs:
https://docs.oracle.com/javase/8/docs/api/javax/swing/JPasswordField.html

**Comment by ahueni** [comment]
It certainly could not do any harm if we changed it ...
This change is now included in the latest commit.
