### ISSUE TITLE
Calibration Multiples

### ISSUE THREAD

**Issue by bbuman** [SPECCHIODB/SPECCHIO#7]
It appears there is an issue with the way calibration files are handled.

Issue:
Even though the calibration file does not change, we end up with several versions of this calibration in the instrumentation admin --> calibrations section. 
Cause:
To be investigated
Force error:
1. Read a couple of CSV files from a specific FloX device. 
2. Read again a couple of CSV files from the same FloX device.
3. Check in the Instrumentation Admin section of the specchio-client, there should appear several calibrations with the same date.

**Comment by ahueni** [comment]
Replicated that error and corrected by specifying the calibration type during insert.
